//this enum contains all the power ups names.

public enum PowerUps{
    //MissilePowerUps
    Missile,
    Mine,
    Flare,
    SupportClaw,
    ElectricClaw,
    BurningClaw,
    RustingClaw,
    //Gadgets
    Turbo,
    TankShield,
    AreaOfHeal,
    Laser,
    Coin,
    //Defense
    Dash,
    HealShield,
    Ghost,
    Hook,
    //Health
    Repair,
    Shield,
    //Drones
    TurretDrone,
    MineDrone,
    GunnerDrone,
    ShieldDrone,
    RepairDrone,
    MissileDrone,
    //BulletTypes
    MissileBullet,
    DrillBullet,
    TrackerBullet,
    //Stats
    MaxHealth,
    MaxSpeed,
    Acceleration,
    RotationSpeed,
    Damage,
    TurretDamage,
    MineDamage,
    MissileDamage,
    DrillDamage,
    ShootSpeed,
    MagazineSize,
    TurretShootSpeed,
    NormalDroneSpeed,
    SpecialDroneSpeed,
    AuxDroneSpeed,
    MaxSpecialAmmo,
    ExtraBullet,
    MaxMines,
    MeleeTime,
    MaxDrones,
}
